# Generated by Django 4.1.1 on 2022-09-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feb', '0002_alter_biodatadosenfeb_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodatamahasiswafeb',
            name='alamat',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='biodatadosenfeb',
            name='alamat',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='biodatatendikfeb',
            name='alamat',
            field=models.TextField(null=True),
        ),
    ]
