# Generated by Django 4.1.1 on 2022-10-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feb', '0005_rename_nip_biodatadosenfeb_nip_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodatadosenfeb',
            name='agama',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='biodatadosenfeb',
            name='jenis_kelamin',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='biodatamahasiswafeb',
            name='agama',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='biodatamahasiswafeb',
            name='jenis_kelamin',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='biodatatendikfeb',
            name='agama',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='biodatatendikfeb',
            name='jenis_kelamin',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
