# Generated by Django 4.1.1 on 2022-10-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feb', '0007_jurusan_jurusanfeb'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodatadosenfeb',
            name='telepon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biodatamahasiswafeb',
            name='telepon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biodatatendikfeb',
            name='telepon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
