# Generated by Django 4.1.1 on 2022-10-08 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feb', '0008_biodatadosenfeb_telepon_biodatamahasiswafeb_telepon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatKul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('keterangan', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatKulfeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jurusan', models.CharField(max_length=50)),
                ('kode_MatKul', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='feb.matkul')),
            ],
        ),
    ]
