# Generated by Django 4.1.1 on 2022-10-11 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feb', '0014_nim_rename_nama_matkul_perkuliahanfeb_nama_ruangan_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Biodatadosenfeb',
            new_name='Biodata_dosen_feb',
        ),
        migrations.RenameModel(
            old_name='Biodatamahasiswafeb',
            new_name='Biodata_mahasiswa_feb',
        ),
        migrations.RenameModel(
            old_name='Biodatatendikfeb',
            new_name='Biodata_tendik_feb',
        ),
        migrations.RenameModel(
            old_name='Fakultasfeb',
            new_name='Fakultas_feb',
        ),
        migrations.RenameModel(
            old_name='Jurusanfeb',
            new_name='Jurusan_feb',
        ),
        migrations.RenameModel(
            old_name='MatKulfeb',
            new_name='MatKul_feb',
        ),
        migrations.RenameModel(
            old_name='Perkuliahanfeb',
            new_name='Perkuliahan_feb',
        ),
        migrations.RenameModel(
            old_name='Userdosenfeb',
            new_name='User_dosen_feb',
        ),
        migrations.RenameModel(
            old_name='Usermahasiswafeb',
            new_name='User_mahasiswa_feb',
        ),
        migrations.RenameModel(
            old_name='Usertendikfeb',
            new_name='User_tendik_feb',
        ),
    ]
