# Generated by Django 4.1.1 on 2022-10-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisip', '0005_rename_nip_biodatadosenfisip_nip_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodatadosenfisip',
            name='agama',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='biodatadosenfisip',
            name='jenis_kelamin',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='biodatamahasiswafisip',
            name='agama',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='biodatamahasiswafisip',
            name='jenis_kelamin',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='biodatatendikfisip',
            name='agama',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='biodatatendikfisip',
            name='jenis_kelamin',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
