# Generated by Django 4.1.1 on 2022-10-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisip', '0007_jurusan_jurusanfisip'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodatadosenfisip',
            name='telepon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biodatamahasiswafisip',
            name='telepon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biodatatendikfisip',
            name='telepon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
