# Generated by Django 4.1.1 on 2022-10-11 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fisip', '0014_nim_rename_nama_matkul_perkuliahanfisip_nama_ruangan_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Biodatamahasiswafisip',
            new_name='Biodata_dosen_fisip',
        ),
        migrations.RenameModel(
            old_name='Biodatadosenfisip',
            new_name='Biodata_mahasiswa_fisip',
        ),
        migrations.RenameModel(
            old_name='Biodatatendikfisip',
            new_name='Biodata_tendik_fisip',
        ),
        migrations.RenameModel(
            old_name='Jurusanfisip',
            new_name='Fakultas_fisip',
        ),
        migrations.RenameModel(
            old_name='Fakultasfisip',
            new_name='Jurusan_fisip',
        ),
        migrations.RenameModel(
            old_name='MatKulfisip',
            new_name='MatKul_fisip',
        ),
        migrations.RenameModel(
            old_name='Perkuliahanfisip',
            new_name='Perkuliahan_fisip',
        ),
        migrations.RenameModel(
            old_name='Userdosenfisip',
            new_name='User_dosen_fisip',
        ),
        migrations.RenameModel(
            old_name='Usermahasiswafisip',
            new_name='User_mahasiswa_fisip',
        ),
        migrations.RenameModel(
            old_name='Usertendikfisip',
            new_name='User_tendik_fisip',
        ),
        migrations.RemoveField(
            model_name='biodata_dosen_fisip',
            name='nim',
        ),
        migrations.RemoveField(
            model_name='biodata_mahasiswa_fisip',
            name='nip_id',
        ),
        migrations.RemoveField(
            model_name='fakultas_fisip',
            name='kode_jurusan',
        ),
        migrations.RemoveField(
            model_name='jurusan_fisip',
            name='kode_fakul',
        ),
        migrations.AddField(
            model_name='biodata_dosen_fisip',
            name='nip_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fisip.nip'),
        ),
        migrations.AddField(
            model_name='biodata_mahasiswa_fisip',
            name='nim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fisip.nim'),
        ),
        migrations.AddField(
            model_name='fakultas_fisip',
            name='kode_fakul',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fisip.fakultas'),
        ),
        migrations.AddField(
            model_name='jurusan_fisip',
            name='kode_jurusan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fisip.jurusan'),
        ),
    ]
