# Generated by Django 4.1.1 on 2022-09-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodatadosenft',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='biodatadosenft',
            name='tanggal_lahir',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='biodatamahasiswaft',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='biodatamahasiswaft',
            name='tanggal_lahir',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='biodatatendikft',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='biodatatendikft',
            name='tanggal_lahir',
            field=models.DateField(),
        ),
    ]
