# Generated by Django 4.1.1 on 2022-10-08 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0010_kelas_perkuliahanfaperta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Perkuliahanfaperta',
            new_name='Perkuliahanft',
        ),
    ]
