# Generated by Django 4.1.1 on 2022-10-11 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ft', '0014_nim_rename_nama_matkul_perkuliahanft_nama_ruangan_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Biodatamahasiswaft',
            new_name='Biodata_dosen_ft',
        ),
        migrations.RenameModel(
            old_name='Biodatadosenft',
            new_name='Biodata_mahasiswa_ft',
        ),
        migrations.RenameModel(
            old_name='Biodatatendikft',
            new_name='Biodata_tendik_ft',
        ),
        migrations.RenameModel(
            old_name='Fakultasft',
            new_name='Fakultas_ft',
        ),
        migrations.RenameModel(
            old_name='Jurusanft',
            new_name='Jurusan_ft',
        ),
        migrations.RenameModel(
            old_name='MatKulft',
            new_name='MatKul_ft',
        ),
        migrations.RenameModel(
            old_name='Perkuliahanft',
            new_name='Perkuliahan_ft',
        ),
        migrations.RenameModel(
            old_name='Usermahasiswaft',
            new_name='User_dosen_ft',
        ),
        migrations.RenameModel(
            old_name='Userdosenft',
            new_name='User_mahasiswa_ft',
        ),
        migrations.RenameModel(
            old_name='Usertendikft',
            new_name='User_tendik_ft',
        ),
        migrations.RemoveField(
            model_name='biodata_dosen_ft',
            name='nim',
        ),
        migrations.RemoveField(
            model_name='biodata_mahasiswa_ft',
            name='nip_id',
        ),
        migrations.RemoveField(
            model_name='user_dosen_ft',
            name='nim_id',
        ),
        migrations.RemoveField(
            model_name='user_mahasiswa_ft',
            name='nip_id',
        ),
        migrations.AddField(
            model_name='biodata_dosen_ft',
            name='nip_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ft.nip'),
        ),
        migrations.AddField(
            model_name='biodata_mahasiswa_ft',
            name='nim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ft.nim'),
        ),
        migrations.AddField(
            model_name='user_dosen_ft',
            name='nip_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ft.nip'),
        ),
        migrations.AddField(
            model_name='user_mahasiswa_ft',
            name='nim_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ft.nim'),
        ),
    ]
