# Generated by Django 4.1.1 on 2022-10-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fh', '0007_jurusan_jurusanfh'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodatadosenfh',
            name='telepon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biodatamahasiswafh',
            name='telepon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biodatatendikfh',
            name='telepon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
