# Generated by Django 4.1.1 on 2022-10-11 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fh', '0014_nim_rename_nama_matkul_perkuliahanfh_nama_ruangan_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Biodatamahasiswafh',
            new_name='Biodata_dosen_fh',
        ),
        migrations.RenameModel(
            old_name='Biodatadosenfh',
            new_name='Biodata_mahasiswa_fh',
        ),
        migrations.RenameModel(
            old_name='Biodatatendikfh',
            new_name='Biodata_tendik_fh',
        ),
        migrations.RenameModel(
            old_name='Jurusanfh',
            new_name='Fakultas_fh',
        ),
        migrations.RenameModel(
            old_name='Fakultasfh',
            new_name='Jurusan_fh',
        ),
        migrations.RenameModel(
            old_name='MatKulfh',
            new_name='MatKul_fh',
        ),
        migrations.RenameModel(
            old_name='Perkuliahanfh',
            new_name='Perkuliahan_fh',
        ),
        migrations.RenameModel(
            old_name='Userdosenfh',
            new_name='User_dosen_fh',
        ),
        migrations.RenameModel(
            old_name='Usertendikfh',
            new_name='User_mahasiswa_fh',
        ),
        migrations.RenameModel(
            old_name='Usermahasiswafh',
            new_name='User_tendik_fh',
        ),
        migrations.RemoveField(
            model_name='biodata_dosen_fh',
            name='nim',
        ),
        migrations.RemoveField(
            model_name='biodata_mahasiswa_fh',
            name='nip_id',
        ),
        migrations.RemoveField(
            model_name='fakultas_fh',
            name='kode_jurusan',
        ),
        migrations.RemoveField(
            model_name='jurusan_fh',
            name='kode_fakul',
        ),
        migrations.RemoveField(
            model_name='user_mahasiswa_fh',
            name='nip_id',
        ),
        migrations.RemoveField(
            model_name='user_tendik_fh',
            name='nim_id',
        ),
        migrations.AddField(
            model_name='biodata_dosen_fh',
            name='nip_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fh.nip'),
        ),
        migrations.AddField(
            model_name='biodata_mahasiswa_fh',
            name='nim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fh.nim'),
        ),
        migrations.AddField(
            model_name='fakultas_fh',
            name='kode_fakul',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fh.fakultas'),
        ),
        migrations.AddField(
            model_name='jurusan_fh',
            name='kode_jurusan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fh.jurusan'),
        ),
        migrations.AddField(
            model_name='user_mahasiswa_fh',
            name='nim_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fh.nim'),
        ),
        migrations.AddField(
            model_name='user_tendik_fh',
            name='nip_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fh.nip'),
        ),
    ]
