# Generated by Django 4.1.1 on 2022-09-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodatamahasiswafaperta',
            name='alamat',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='biodatadosenfaperta',
            name='alamat',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='biodatadosenfaperta',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='biodatadosenfaperta',
            name='tanggal_lahir',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='biodatamahasiswafaperta',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='biodatamahasiswafaperta',
            name='tanggal_lahir',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='biodatatendikfaperta',
            name='alamat',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='biodatatendikfaperta',
            name='photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='biodatatendikfaperta',
            name='tanggal_lahir',
            field=models.DateField(),
        ),
    ]
