# Generated by Django 4.1.1 on 2022-10-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faperta', '0006_jurusan_jurusanfaperta'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodatadosenfaperta',
            name='telepon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biodatamahasiswafaperta',
            name='telepon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biodatatendikfaperta',
            name='telepon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
