# Generated by Django 4.1.1 on 2022-09-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biodatadosenfkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.IntegerField()),
                ('nama', models.CharField(max_length=100)),
                ('tanggal_lahir', models.IntegerField()),
                ('photo', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('fakultas', models.CharField(max_length=100)),
                ('prodi', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Biodatamahasiswafkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.IntegerField()),
                ('nama', models.CharField(max_length=100)),
                ('tanggal_lahir', models.IntegerField()),
                ('photo', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('fakultas', models.CharField(max_length=100)),
                ('prodi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Biodatatendikfkip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nip', models.IntegerField()),
                ('nama', models.CharField(max_length=100)),
                ('tanggal_lahir', models.IntegerField()),
                ('photo', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=100)),
                ('alamat', models.CharField(max_length=200)),
            ],
        ),
    ]
