# Generated by Django 4.1.1 on 2022-09-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fkip', '0002_alter_biodatadosenfkip_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodatamahasiswafkip',
            name='alamat',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='biodatadosenfkip',
            name='alamat',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='biodatatendikfkip',
            name='alamat',
            field=models.TextField(null=True),
        ),
    ]
