# Generated by Django 4.1.1 on 2022-10-11 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fkip', '0014_nim_rename_nama_matkul_perkuliahanfkip_nama_ruangan_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Biodatamahasiswafkip',
            new_name='Biodata_dosen_fkip',
        ),
        migrations.RenameModel(
            old_name='Biodatadosenfkip',
            new_name='Biodata_mahasiswa_fkip',
        ),
        migrations.RenameModel(
            old_name='Biodatatendikfkip',
            new_name='Biodata_tendik_fkip',
        ),
        migrations.RenameModel(
            old_name='Jurusanfkip',
            new_name='Fakultas_fkip',
        ),
        migrations.RenameModel(
            old_name='Fakultasfkip',
            new_name='Jurusan_fkip',
        ),
        migrations.RenameModel(
            old_name='MatKulfkip',
            new_name='MatKul_fkip',
        ),
        migrations.RenameModel(
            old_name='Perkuliahanfkip',
            new_name='Perkuliahan_fkip',
        ),
        migrations.RenameModel(
            old_name='Usermahasiswafkip',
            new_name='User_dosen_fkip',
        ),
        migrations.RenameModel(
            old_name='Userdosenfkip',
            new_name='User_mahasiswa_fkip',
        ),
        migrations.RenameModel(
            old_name='Usertendikfkip',
            new_name='User_tendik_fkip',
        ),
        migrations.RemoveField(
            model_name='biodata_dosen_fkip',
            name='nim',
        ),
        migrations.RemoveField(
            model_name='biodata_mahasiswa_fkip',
            name='nip_id',
        ),
        migrations.RemoveField(
            model_name='fakultas_fkip',
            name='kode_jurusan',
        ),
        migrations.RemoveField(
            model_name='jurusan_fkip',
            name='kode_fakul',
        ),
        migrations.RemoveField(
            model_name='user_dosen_fkip',
            name='nim_id',
        ),
        migrations.RemoveField(
            model_name='user_mahasiswa_fkip',
            name='nip_id',
        ),
        migrations.AddField(
            model_name='biodata_dosen_fkip',
            name='nip_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fkip.nip'),
        ),
        migrations.AddField(
            model_name='biodata_mahasiswa_fkip',
            name='nim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fkip.nim'),
        ),
        migrations.AddField(
            model_name='fakultas_fkip',
            name='kode_fakul',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fkip.fakultas'),
        ),
        migrations.AddField(
            model_name='jurusan_fkip',
            name='kode_jurusan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fkip.jurusan'),
        ),
        migrations.AddField(
            model_name='user_dosen_fkip',
            name='nip_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fkip.nip'),
        ),
        migrations.AddField(
            model_name='user_mahasiswa_fkip',
            name='nim_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fkip.nim'),
        ),
    ]
