# Generated by Django 4.1.1 on 2022-09-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fk', '0002_alter_biodatadosenfk_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodatamahasiswafk',
            name='alamat',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='biodatadosenfk',
            name='alamat',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='biodatatendikfk',
            name='alamat',
            field=models.TextField(null=True),
        ),
    ]
