# Generated by Django 4.1.1 on 2022-10-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fk', '0007_jurusan_jurusanfk'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodatadosenfk',
            name='telepon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biodatamahasiswafk',
            name='telepon',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biodatatendikfk',
            name='telepon',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
