# Generated by Django 4.1.1 on 2022-09-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pascasarjana', '0002_alter_biodatadosenpasca_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodatamahasiswapasca',
            name='alamat',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='biodatadosenpasca',
            name='alamat',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='biodatatendikpasca',
            name='alamat',
            field=models.TextField(null=True),
        ),
    ]
