# Generated by Django 4.1.1 on 2022-10-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pascasarjana', '0005_rename_nip_biodatadosenpasca_nip_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodatadosenpasca',
            name='agama',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='biodatamahasiswapasca',
            name='agama',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='biodatatendikpasca',
            name='agama',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
