# Generated by Django 4.1.1 on 2022-10-11 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pascasarjana', '0014_nim_rename_nama_matkul_perkuliahanpasca_nama_ruangan_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Biodatamahasiswapasca',
            new_name='Biodata_dosen_pasca',
        ),
        migrations.RenameModel(
            old_name='Biodatadosenpasca',
            new_name='Biodata_mahasiswa_pasca',
        ),
        migrations.RenameModel(
            old_name='Biodatatendikpasca',
            new_name='Biodata_tendik_pasca',
        ),
        migrations.RenameModel(
            old_name='Jurusanpasca',
            new_name='Fakultas_pasca',
        ),
        migrations.RenameModel(
            old_name='Fakultaspasca',
            new_name='Jurusan_pasca',
        ),
        migrations.RenameModel(
            old_name='MatKulpasca',
            new_name='MatKul_pasca',
        ),
        migrations.RenameModel(
            old_name='Perkuliahanpasca',
            new_name='Perkuliahan_pasca',
        ),
        migrations.RenameModel(
            old_name='Usertendikpasca',
            new_name='User_dosen_pasca',
        ),
        migrations.RenameModel(
            old_name='Userdosenpasca',
            new_name='User_mahasiswa_pasca',
        ),
        migrations.RenameModel(
            old_name='Usermahasiswapasca',
            new_name='User_tendik_pasca',
        ),
        migrations.RemoveField(
            model_name='biodata_dosen_pasca',
            name='nim',
        ),
        migrations.RemoveField(
            model_name='biodata_mahasiswa_pasca',
            name='nip_id',
        ),
        migrations.RemoveField(
            model_name='fakultas_pasca',
            name='kode_jurusan',
        ),
        migrations.RemoveField(
            model_name='jurusan_pasca',
            name='kode_fakul',
        ),
        migrations.RemoveField(
            model_name='user_mahasiswa_pasca',
            name='nip_id',
        ),
        migrations.RemoveField(
            model_name='user_tendik_pasca',
            name='nim_id',
        ),
        migrations.AddField(
            model_name='biodata_dosen_pasca',
            name='nip_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pascasarjana.nip'),
        ),
        migrations.AddField(
            model_name='biodata_mahasiswa_pasca',
            name='nim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pascasarjana.nim'),
        ),
        migrations.AddField(
            model_name='fakultas_pasca',
            name='kode_fakul',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pascasarjana.fakultas'),
        ),
        migrations.AddField(
            model_name='jurusan_pasca',
            name='kode_jurusan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pascasarjana.jurusan'),
        ),
        migrations.AddField(
            model_name='user_mahasiswa_pasca',
            name='nim_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pascasarjana.nim'),
        ),
        migrations.AddField(
            model_name='user_tendik_pasca',
            name='nip_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pascasarjana.nip'),
        ),
    ]
